from __future__ import annotations

from sqlalchemy import (
    Column,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

state_meta = Table(
    "state_meta",
    metadata,
    Column("key", String, primary_key=True),
    Column("value_json", Text, nullable=False),
    Column("updated_at", String, nullable=False),
)

agents = Table(
    "agents",
    metadata,
    Column("id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("normalized_name", String, nullable=False),
    Column("description", Text, nullable=True),
    Column("backend", String, nullable=False),
    Column("model", String, nullable=True),
    Column("reasoning_effort", String, nullable=True),
    Column("system_prompt", Text, nullable=True),
    Column("source", String, nullable=False),
    Column("source_ref", Text, nullable=True),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    UniqueConstraint("normalized_name", name="uq_agents_normalized_name"),
    Index("ix_agents_backend", "backend"),
    Index("ix_agents_updated", "updated_at"),
)

scopes = Table(
    "scopes",
    metadata,
    Column("id", String, primary_key=True),
    Column("platform", String, nullable=False),
    Column("scope_type", String, nullable=False),
    Column("native_id", String, nullable=False),
    Column("parent_scope_id", String, ForeignKey("scopes.id", ondelete="SET NULL"), nullable=True),
    Column("display_name", Text, nullable=True),
    Column("native_type", String, nullable=True),
    Column("is_private", Integer, nullable=False),
    Column("supports_threads", Integer, nullable=False),
    Column("metadata_json", Text, nullable=False),
    Column("first_seen_at", String, nullable=False),
    Column("last_seen_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    UniqueConstraint("platform", "scope_type", "native_id", name="uq_scopes_platform_type_native"),
    Index("ix_scopes_platform_type", "platform", "scope_type"),
    Index("ix_scopes_parent", "parent_scope_id"),
)

scope_settings = Table(
    "scope_settings",
    metadata,
    Column("scope_id", String, ForeignKey("scopes.id", ondelete="CASCADE"), primary_key=True),
    Column("enabled", Integer, nullable=False),
    Column("role", String, nullable=True),
    Column("workdir", Text, nullable=True),
    Column("agent_name", String, nullable=True),
    Column("agent_backend", String, nullable=True),
    Column("agent_variant", String, nullable=True),
    Column("model", String, nullable=True),
    Column("reasoning_effort", String, nullable=True),
    Column("require_mention", Integer, nullable=True),
    Column("settings_version", Integer, nullable=False),
    Column("settings_json", Text, nullable=False),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("ix_scope_settings_role", "role"),
    Index("ix_scope_settings_workdir", "workdir"),
    Index("ix_scope_settings_backend_model", "agent_backend", "model"),
)

auth_codes = Table(
    "auth_codes",
    metadata,
    Column("code", String, primary_key=True),
    Column("type", String, nullable=False),
    Column("is_active", Integer, nullable=False),
    Column("expires_at", String, nullable=True),
    Column("used_by_json", Text, nullable=False),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
)

agent_sessions = Table(
    "agent_sessions",
    metadata,
    Column("id", String, primary_key=True),
    Column("scope_id", String, ForeignKey("scopes.id", ondelete="SET NULL"), nullable=True),
    Column("agent_id", String, nullable=True),
    Column("agent_name", String, nullable=True),
    Column("agent_backend", String, nullable=False),
    Column("agent_variant", String, nullable=False),
    Column("model", String, nullable=True),
    Column("reasoning_effort", String, nullable=True),
    Column("session_anchor", String, nullable=False),
    Column("workdir", Text, nullable=True),
    Column("native_session_id", Text, nullable=False),
    Column("title", Text, nullable=True),
    Column("status", String, nullable=False),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Column("last_active_at", String, nullable=True),
    Index("ix_agent_sessions_scope_anchor_workdir", "scope_id", "session_anchor", "workdir"),
    Index("ix_agent_sessions_backend_variant", "agent_backend", "agent_variant"),
    Index("ix_agent_sessions_status_activity", "status", "last_active_at"),
    Index("ix_agent_sessions_native_session", "native_session_id"),
)

runtime_records = Table(
    "runtime_records",
    metadata,
    Column("id", String, primary_key=True),
    Column("record_type", String, nullable=False),
    Column("record_key", String, nullable=False),
    Column("scope_id", String, ForeignKey("scopes.id", ondelete="SET NULL"), nullable=True),
    Column("session_anchor", String, nullable=True),
    Column("workdir", Text, nullable=True),
    Column("payload_json", Text, nullable=False),
    Column("expires_at", String, nullable=True),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    UniqueConstraint("record_type", "record_key", name="uq_runtime_records_type_key"),
    Index("ix_runtime_records_type_scope_expiry", "record_type", "scope_id", "expires_at"),
    Index("ix_runtime_records_scope_anchor", "scope_id", "session_anchor"),
    Index("ix_runtime_records_workdir", "workdir"),
)

run_definitions = Table(
    "run_definitions",
    metadata,
    Column("id", String, primary_key=True),
    Column("definition_type", String, nullable=False),
    Column("name", Text, nullable=True),
    Column("agent_name", String, nullable=True),
    Column("session_policy", String, nullable=True),
    Column("session_id", String, nullable=True),
    Column("legacy_session_key", Text, nullable=True),
    Column("prompt", Text, nullable=True),
    Column("message", Text, nullable=True),
    Column("message_payload_json", Text, nullable=True),
    Column("schedule_type", String, nullable=True),
    Column("cron", Text, nullable=True),
    Column("run_at", String, nullable=True),
    Column("timezone", String, nullable=True),
    Column("command_json", Text, nullable=True),
    Column("shell_command", Text, nullable=True),
    Column("prefix", Text, nullable=True),
    Column("cwd", Text, nullable=True),
    Column("mode", String, nullable=True),
    Column("timeout_seconds", Float, nullable=True),
    Column("lifetime_timeout_seconds", Float, nullable=True),
    Column("retry_exit_codes_json", Text, nullable=True),
    Column("retry_delay_seconds", Float, nullable=True),
    Column("post_to", String, nullable=True),
    Column("deliver_key", Text, nullable=True),
    Column("enabled", Integer, nullable=False),
    Column("deleted_at", String, nullable=True),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Column("last_started_at", String, nullable=True),
    Column("last_finished_at", String, nullable=True),
    Column("last_event_at", String, nullable=True),
    Column("last_run_at", String, nullable=True),
    Column("last_error", Text, nullable=True),
    Column("last_exit_code", Integer, nullable=True),
    Column("last_run_id", String, nullable=True),
    Column("metadata_json", Text, nullable=False),
    Index("ix_run_definitions_type_enabled", "definition_type", "enabled"),
    Index("ix_run_definitions_session", "session_id"),
    Index("ix_run_definitions_agent", "agent_name"),
    Index("ix_run_definitions_updated", "updated_at"),
)

agent_runs = Table(
    "agent_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("definition_id", String, nullable=True),
    Column("run_type", String, nullable=False),
    Column("status", String, nullable=False),
    Column("source_kind", String, nullable=True),
    Column("source_actor", Text, nullable=True),
    Column("parent_run_id", String, nullable=True),
    Column("agent_name", String, nullable=True),
    Column("agent_id", String, nullable=True),
    Column("agent_backend", String, nullable=True),
    Column("model", String, nullable=True),
    Column("reasoning_effort", String, nullable=True),
    Column("session_policy", String, nullable=True),
    Column("session_id", String, nullable=True),
    Column("legacy_session_key", Text, nullable=True),
    Column("post_to", String, nullable=True),
    Column("deliver_key", Text, nullable=True),
    Column("prompt", Text, nullable=True),
    Column("message", Text, nullable=True),
    Column("message_payload_json", Text, nullable=True),
    Column("result_text", Text, nullable=True),
    Column("result_payload_json", Text, nullable=True),
    Column("message_ids_json", Text, nullable=True),
    Column("cancel_requested", Integer, nullable=False, default=0),
    Column("cancel_requested_at", String, nullable=True),
    Column("pid", Integer, nullable=True),
    Column("exit_code", Integer, nullable=True),
    Column("error", Text, nullable=True),
    Column("stdout", Text, nullable=True),
    Column("stderr", Text, nullable=True),
    Column("created_at", String, nullable=False),
    Column("started_at", String, nullable=True),
    Column("completed_at", String, nullable=True),
    Column("updated_at", String, nullable=False),
    Column("metadata_json", Text, nullable=False),
    Index("ix_agent_runs_definition_created", "definition_id", "created_at"),
    Index("ix_agent_runs_status_created", "status", "created_at"),
    Index("ix_agent_runs_type_status_created", "run_type", "status", "created_at"),
    Index("ix_agent_runs_session_created", "session_id", "created_at"),
    Index("ix_agent_runs_agent_created", "agent_name", "created_at"),
)

# Backwards-compatible Python aliases for legacy callers. The physical table
# names are the new domain names.
background_tasks = run_definitions
background_runs = agent_runs

show_pages = Table(
    "show_pages",
    metadata,
    Column("session_id", String, primary_key=True),
    Column("visibility", String, nullable=False),
    Column("share_id", String, nullable=True),
    Column("offline_at", String, nullable=True),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    UniqueConstraint("share_id", name="uq_show_pages_share_id"),
    Index("ix_show_pages_share_id", "share_id"),
    Index("ix_show_pages_visibility", "visibility"),
)

imported_state_tables = [
    show_pages,
    background_runs,
    background_tasks,
    scope_settings,
    auth_codes,
    agent_sessions,
    runtime_records,
    scopes,
]
