"""Helpers for writing Codex's on-disk auth configuration.

The Codex CLI / ``codex app-server`` reads two files at launch time:

- ``~/.codex/config.toml`` — model + provider preferences (including the
  ``model_provider`` selector and the ``[model_providers.<id>]`` table that
  carries ``base_url``).
- ``~/.codex/auth.json`` — credential bag; the ``OPENAI_API_KEY`` field is
  the one Codex consumes for API-key mode.

This module mediates writes to those files so the Settings → Backends →
Codex UI can flip between OAuth (ChatGPT login) and API-key modes without
the user dropping into a terminal. The persistent app-server picks up
changes via ``restart_backend('codex')``.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Provider id we manage in ``[model_providers.<id>]``. Codex ships with a
# built-in ``openai`` provider; if the user has hand-edited that block we
# leave their fields alone except for ``base_url`` when one is supplied.
MANAGED_PROVIDER_ID = "openai"


def get_codex_home(home: Path | None = None) -> Path:
    return (home or Path.home()) / ".codex"


def get_codex_config_paths(home: Path | None = None) -> tuple[Path, Path]:
    """Return ``(config.toml, auth.json)`` paths under ``~/.codex``."""
    codex_home = get_codex_home(home)
    return codex_home / "config.toml", codex_home / "auth.json"


def _load_toml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        try:
            import tomllib  # type: ignore[attr-defined]
        except Exception:  # pragma: no cover - py<3.11 fallback
            import tomli as tomllib  # type: ignore[no-redef]
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        logger.warning("Codex config.toml parse failed (%s); rewriting from empty", exc)
        return {}


def _load_auth(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return data
    except Exception as exc:
        logger.warning("Codex auth.json parse failed (%s); rewriting from empty", exc)
    return {}


def _dump_toml_value(value: Any) -> str:
    """Serialize a single scalar value back to TOML. Tables handled separately."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, list):
        return "[" + ", ".join(_dump_toml_value(item) for item in value) + "]"
    # Fallback: serialize as JSON-ish string (best-effort for unexpected types).
    return _dump_toml_value(json.dumps(value))


def _dump_toml(data: Dict[str, Any]) -> str:
    """Minimal TOML emitter for the Codex config shape we manage.

    Handles top-level scalars and one level of nested tables
    (``[a.b]``). Comments and original ordering are lost — acceptable
    here because the file is typically generated by ``codex login`` and
    re-rendered round-trip with our managed fields.
    """
    lines: list[str] = []
    nested: list[tuple[str, Dict[str, Any]]] = []
    for key, value in data.items():
        if isinstance(value, dict):
            nested.append((key, value))
            continue
        lines.append(f"{key} = {_dump_toml_value(value)}")
    for parent, subtree in nested:
        # ``subtree`` may itself be either scalars (one ``[parent]`` table)
        # or a dict of named subtables (``[parent.child]``).
        scalar_children: list[tuple[str, Any]] = []
        table_children: list[tuple[str, Dict[str, Any]]] = []
        for child_key, child_value in subtree.items():
            if isinstance(child_value, dict):
                table_children.append((child_key, child_value))
            else:
                scalar_children.append((child_key, child_value))
        if scalar_children:
            lines.append("")
            lines.append(f"[{parent}]")
            for child_key, child_value in scalar_children:
                lines.append(f"{child_key} = {_dump_toml_value(child_value)}")
        for child_key, grandchildren in table_children:
            lines.append("")
            lines.append(f"[{parent}.{child_key}]")
            for grand_key, grand_value in grandchildren.items():
                if isinstance(grand_value, dict):
                    # Codex doesn't currently nest deeper than two levels in
                    # the surface we manage; punt on deeper nesting.
                    logger.debug(
                        "Skipping deeply-nested TOML entry %s.%s.%s", parent, child_key, grand_key
                    )
                    continue
                lines.append(f"{grand_key} = {_dump_toml_value(grand_value)}")
    return "\n".join(lines) + ("\n" if lines else "")


def _atomic_write(path: Path, content: str, *, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    try:
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:  # pragma: no cover - best effort cleanup
                pass
    try:
        path.chmod(mode)
    except OSError as exc:  # pragma: no cover - non-POSIX
        logger.debug("chmod %s failed: %s", path, exc)


def apply_codex_auth(
    *,
    auth_mode: str,
    api_key: Optional[str],
    base_url: Optional[str],
    home: Path | None = None,
) -> None:
    """Persist the requested auth mode into Codex's on-disk config files.

    - ``api_key`` mode: write ``OPENAI_API_KEY`` into ``auth.json``,
      optionally set ``[model_providers.openai].base_url`` if a non-default
      URL was supplied, and pin top-level ``model_provider = "openai"`` so
      Codex actually uses the keyed provider.
    - ``oauth`` mode: drop ``OPENAI_API_KEY`` from ``auth.json``, leave any
      ``tokens`` blob in place, and clear our managed ``base_url`` so the
      next launch goes back to OpenAI's default endpoint.
    """
    if auth_mode not in {"oauth", "api_key"}:
        raise ValueError(f"Unsupported codex auth_mode: {auth_mode!r}")

    config_path, auth_path = get_codex_config_paths(home)
    auth_data = _load_auth(auth_path)
    toml_data = _load_toml(config_path)

    providers = toml_data.setdefault("model_providers", {})
    if not isinstance(providers, dict):
        providers = {}
        toml_data["model_providers"] = providers
    managed = providers.setdefault(MANAGED_PROVIDER_ID, {})
    if not isinstance(managed, dict):
        managed = {}
        providers[MANAGED_PROVIDER_ID] = managed

    if auth_mode == "api_key":
        if not api_key:
            raise ValueError("api_key is required when auth_mode='api_key'")
        auth_data["OPENAI_API_KEY"] = api_key
        toml_data["model_provider"] = MANAGED_PROVIDER_ID
        managed.setdefault("name", "OpenAI")
        if base_url:
            managed["base_url"] = base_url
        else:
            managed.pop("base_url", None)
    else:  # oauth
        auth_data.pop("OPENAI_API_KEY", None)
        # Leave model_provider as-is — switching back to ChatGPT/OAuth is
        # the user's responsibility via ``codex login``; we just stop
        # pinning the keyed provider's overrides.
        managed.pop("base_url", None)
        # If our managed entry is now empty, drop it entirely so we don't
        # leave a noisy ``[model_providers.openai]`` table behind.
        if not managed:
            providers.pop(MANAGED_PROVIDER_ID, None)
            if not providers:
                toml_data.pop("model_providers", None)

    _atomic_write(auth_path, json.dumps(auth_data, indent=2) + "\n", mode=0o600)
    _atomic_write(config_path, _dump_toml(toml_data), mode=0o600)


def read_codex_auth_state(home: Path | None = None) -> Dict[str, Any]:
    """Return the user-visible auth state for the Settings UI.

    Reads both files and reports back what the user would see — no
    secrets in the response (the UI receives the key length, never the
    plaintext key).
    """
    config_path, auth_path = get_codex_config_paths(home)
    auth_data = _load_auth(auth_path)
    toml_data = _load_toml(config_path)
    api_key = auth_data.get("OPENAI_API_KEY")
    has_chatgpt_tokens = isinstance(auth_data.get("tokens"), dict)

    providers = toml_data.get("model_providers")
    base_url: Optional[str] = None
    if isinstance(providers, dict):
        managed = providers.get(MANAGED_PROVIDER_ID)
        if isinstance(managed, dict):
            raw = managed.get("base_url")
            if isinstance(raw, str) and raw.strip():
                base_url = raw.strip()

    inferred_mode = "api_key" if isinstance(api_key, str) and api_key else "oauth"
    return {
        "auth_mode": inferred_mode,
        "has_api_key": isinstance(api_key, str) and bool(api_key),
        "api_key_length": len(api_key) if isinstance(api_key, str) else 0,
        "base_url": base_url,
        "has_chatgpt_tokens": has_chatgpt_tokens,
    }
